FROM node:22-alpine

WORKDIR /app

COPY package.json ./
COPY api/package.json ./api/
COPY worker/package.json ./worker/
COPY web/package.json ./web/
COPY packages/shared/package.json ./packages/shared/

RUN npm install --workspaces --include-workspace-root

COPY packages/shared ./packages/shared
COPY worker ./worker

WORKDIR /app/worker

CMD ["npm", "run", "dev"]
